// <auto-generated />
using System;
using AssesmentAGIT.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssesmentAGIT.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssesmentAGIT.Domain.Entities.Planning", b =>
                {
                    b.Property<Guid>("PlanningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PlanningId");

                    b.HasIndex("RequestCode")
                        .IsUnique();

                    b.ToTable("Plannings");
                });

            modelBuilder.Entity("AssesmentAGIT.Domain.Entities.PlanningSlot", b =>
                {
                    b.Property<Guid>("PlanningSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BalancedQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("OriginalQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PlanningId")
                        .HasColumnType("uuid");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SlotOrder")
                        .HasColumnType("integer");

                    b.HasKey("PlanningSlotId");

                    b.HasIndex("PlanningId");

                    b.ToTable("PlanningSlots", t =>
                        {
                            t.HasCheckConstraint("CK_PlanningSlot_BalancedQuantity_NonNegative", "\"BalancedQuantity\" >= 0");

                            t.HasCheckConstraint("CK_PlanningSlot_OriginalQuantity_NonNegative", "\"OriginalQuantity\" >= 0");
                        });
                });

            modelBuilder.Entity("AssesmentAGIT.Domain.Entities.PlanningSlot", b =>
                {
                    b.HasOne("AssesmentAGIT.Domain.Entities.Planning", "Planning")
                        .WithMany("Slots")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("AssesmentAGIT.Domain.Entities.Planning", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
